volumes:
  mongodb_data:
  rabbitmq_data:
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: warkaa
      MONGO_INITDB_ROOT_USERNAME: m0ng0db
      MONGO_INITDB_ROOT_PASSWORD: p4ssw0rd
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:management-alpine
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: '10s'
      timeout: '5s'
      retries: 5
    ports:
      - 5672:5672
      - 15672:15672
