volumes:
  mongodb_data:
    driver: local
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: warkaa
      MONGO_INITDB_ROOT_USERNAME: m0ng0db
      MONGO_INITDB_ROOT_PASSWORD: p4ssw0rd
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5